### PR TITLE
detailPanelDefaultToggle property. 

### PR DESCRIPTION
**Pull request by edgar-arroyo-by**
## Description
There are two ways to open a detail panel:

1. With the arrows that are added at the side of the rows when users set a detail panel
2. With the onrowClick method, that has as an argument the function to open a detail panel

Let put a simple case, i want to have just one detail panel oppened at a time. This is easy to achieve using the onrowClick, but, what is the problem?

That we can manage the logic of when-to-open with the onrowClick but not with the arrows. That means that when user clicks on arrow, it will not respect the onrowclick logic.

**how can this be solved**
adding this prop `detailPanelDefaultToggle` that is `true` by default (so everything keeps normal and we do not add breaking changes)

if devs sets `detailPanelDefaultToggle` to `false`, then the arrow will do nothing but being a visual status of the state of the detail panel and then the dev will manage the toggling with other thing (onRowClick nowadays)

And, this do not add breaking changes.

## Impacted Areas in Application

List general components of the application that this PR will affect:

- MTableBodyRow

### CODE REVIEW

**Comment by Domino987** [comment]
There is the option to enable only one panel to be open: `detailPanelType`.
Would that work for you too?
https://github.com/material-table-core/core/blob/master/types/index.d.ts#L340

**Comment by edgar-arroyo-by** [comment]
hello @Domino987!
For that particular case, it will 👯 

But, i do not if detailPanelType is scalable for the future and the creation of other cases. I dunot, like maybe in the future someone just one to have detail panels if the data has a property or if its the first row, something like that 


Thanks a lot in advance!

**Comment by Domino987** [comment]
That is true, might be a bit of premature optimization here, but I think we should adjust a few things. 
We would need to add the the prop to the types as well.
Also the naming might be a bit inaccurate.

But I think we should address this use case when it arises, not prior for hypothetical ones.
WHat do you think?

**Comment by edgar-arroyo-by** [comment]
Agree that the naming is innacurate :D
What name for the prop do you suggest?

Another question, how can i add the types? 👯‍♂️ 
And finally, I think the case is already arised 👯‍♂️  Summarized it is:
As a dev, I want to control de toggling with the onrowclick, but not with the arrows, based on the row data.

Thanks a lot for everything @Domino987!

**Comment by Domino987** [comment]
Not yet for the name.
For the types, you need to go into the types folder/index and add the types there, e.g. here in options.

Regarding the use case, it was solved using the single prop, and it can also be achieved by hiding the detail panel icon and add a custom action as well, so maybe I just dont see the benefit of this.
But if you have a usecase that cannot be done currently, I would be glad to hear it.

**Pull request closed without merging**
