### PR TITLE
chore: change transpiler

### PR DESCRIPTION
**Pull request by matthewoestreich**
- remove babel config and references to babel in package.json
- add esbuild

### See Discussion #289 

@Domino987

### CODE REVIEW

**Review by Domino987 — APPROVED** [review]

**Comment by Domino987** [comment]
Hmh seems like the build config fails. Do you know why that is ?

**Comment by matthewoestreich** [comment]
Yea just figured out why.. It's because when you specify `"type": "module"` it doesn't allow you to use `require` anywhere in the project. The node script I run, which uses `esbuild` uses `require`. I removed the `"type": "module"` since one can safely assume if you're writing React, you have a way to transpile already.

I think it failed the second time because somewhere something is still looking for a Babel config file when we run it thru GH actions. I wonder if that's something GH actions requires?

The real advantage is the speed and output size of esbuild.

**Comment by matthewoestreich** [comment]
It's especially odd bc all of the build steps worked fine locally. The only time there's an error about missing `babel.config.js` is on GH actions (as far as I can tell).  We shouldn't need Babel, I don't think..

**Comment by Domino987** [comment]
Hmh that's weird. But if the release works it should be fine.

**Comment by matthewoestreich** [comment]
Looks like Jest uses it.. When I remove `babel.config.js` and do `npm run test` - it fails with the same error.

**Comment by matthewoestreich** [comment]
I will go ahead and merge, then publish a new major version.

**Comment by matthewoestreich** [comment]
@Domino987 I also upgraded `@material-table/core` to the latest `v4.0.0` on the website and there don't appear to be any issues.

(fingers crossed)

**Comment by Domino987** [comment]
Awesome. Thanks for this

**Comment by matthewoestreich** [comment]
You bet. Now our package is half the size! Crazy.

**Pull request merged**
