### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by Domino987**
## Description

@oze4  What do you think?

### CODE REVIEW

**Comment by matthewoestreich** [comment]
Amazing as always, my friend!  Makes it easier, too. I really, really like what you've done.

**Review by matthewoestreich — APPROVED** [review]

**Comment by Domino987** [comment]
Maybe I need to reduce the version again 😅

**Comment by matthewoestreich** [comment]
What do you mean? Why would you need to reduce the version? Only asking because I can't see the reason lol Everything seems good to me.

**Comment by matthewoestreich** [comment]
But I do need to update the contributing/publishing guide because you've made that a lot easier.

**Comment by Domino987** [comment]
I updated the version twice I think. I will update the contribution file.

**Comment by matthewoestreich** [comment]
I added those changes to this PR. So the Publishing guide is updated.

**Comment by Domino987** [comment]
Yes, these look nice. Merging?

**Pull request merged**
