### PR TITLE
Access bulk edit on render

### LINKED ISSUE #104: Bulk update behaviour
# Guidelines

- #### Please include a demo of the issue/behavior/question you have

- #### Please try to be as detailed as possible

I have a functional component which uses MT's bulk update feature. Everything works as expected so, no issues there though... What I noticed is, after clicking the 'Edit' (Pencil Icon) button on the top right corner, all editable elements get enabled for the user input and user can update values in those elements. The issue is, user MUST click the tick (correct icon) in order to ACCEPT those changes, if user miss to ACCEPT those changes and move to the next\previous page or say click a command button on the page, user will end up losing their changes. 

Is there any way to force user to ACCEPT or REJECT their changes when they perform activities like this? i.e. clicking any other button etc? I have a SAVE and CANCEL command buttons to save changes to the database via API, Ideally I would like to ACCEPT all outstanding changes on the page before running button's click handler.

- #### You may fork one of the following starter templates if you would like:

  - #### [CodeSandbox](https://codesandbox.io/s/material-table-starter-template-xnfpo)
  - #### [StackBlitz](https://stackblitz.com/edit/material-table-starter-template)

### PR DESCRIPTION
**Pull request by Domino987**
## Related Issue

Fixes #104

## Description

Upon paging and bulk editing, the newly edited values will be shown instead of the base value of the cell.

### CODE REVIEW

**Comment by Domino987** [comment]
@oze4

**Comment by matthewoestreich** [comment]
@Domino987 I say if you feel comfortable pushing any code, go for it my friend. You should have proper access for that (I don't want to be a bottleneck). The truth is you know more about the codebase than I do, so your judgement is going to be better than mine.

**Review by matthewoestreich — APPROVED** [review]

**Comment by Domino987** [comment]
@oze4 I do but I still don't want to just push code without some kind of checks. So it won't be like the stuff mbrn did .

**Comment by Domino987** [comment]
You are greatly appreciate.  Let's get this take off

**Comment by matthewoestreich** [comment]
@Domino987 that makes sense, I see what you mean now. I feel bad for just pushing code, without your buyoff, like I have in the past.  I apologize. I will no longer push any code wo your buyoff.  

You too my friend, you are appreciated greatly as well!  :)

**Comment by Domino987** [comment]
@oze4 no that's not a problem. Pushing code. Pls do. I just want some kind of feedback if I missed anything.  Always waiting would just create a new bottle neck.

**Pull request merged**
