### PR TITLE
Remove deepclone for persist columns

### PR DESCRIPTION
**Pull request by Domino987**
## Description

Removes deepclone for persist columns with local storage. 
Link to [Discussion](https://github.com/material-table-core/core/commit/eae061feac5b7a14c1baea8bd8e40217e71a59c0#r57327695).

### CODE REVIEW

**Comment by peacechen** [comment]
The logic changes in this PR may introduce unintended side effects.

**Comment by Domino987** [comment]
> The logic changes in this PR may introduce unintended side effects.

Since this addition is relatively new in the first place.
I don't think there are side effects in these latest changes of this PR. But if you find any side effects, let me know :)

**Review by edgar-arroyo-by — APPROVED** [review]

**Comment by edgar-arroyo-by** [comment]
Hello @Domino987 

friendly reminder of this branch

**Comment by Domino987** [comment]
Yes, I am aware but I am still looking into it to see if we have some kind of regression. Will merge this week.

**Comment by Domino987** [comment]
@FalkF Could you take a look at it if you see a problem with your initial implementation?

**Comment by FalkF** [comment]
Yes, I will take a look! Sorry for the extra work!

**Comment by Domino987** [comment]
No problem, still a great feature !

**Comment by Domino987** [comment]
> Yes, I will take a look! Sorry for the extra work!

@FalkF ping 😉

**Pull request merged**
