### PR TITLE
Include selected data in exportFunc

### PR DESCRIPTION
**Pull request by zwagner86**
## Related Issue

Relate the Github issue with this PR using `#`

## Description

exportFunc receives searched and filtered data and I think it should also receive selected data

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Impacted Areas in Application

List general components of the application that this PR will affect:

\* MTableToolbar

## Additional Notes

This is optional, feel free to follow your heart and write here :)

### CODE REVIEW

**Review by Domino987 — APPROVED** [review]

**Comment by Domino987** [comment]
Thank you

**Comment by Domino987** [comment]
Seems like some test dont work. Can you check it? @zwagner86

**Comment by zwagner86** [comment]
@Domino987 - I didn't see any test failures on my side, but then I did and attempted to fix.  Then my fork was out of date so i synced and realized that my test fixes were not required.  So, in short, I am back to not seeing any test failures on my end.

**Review by Domino987 — APPROVED** [review]

**Comment by Domino987** [comment]
Thank you!

**Pull request merged**
