### PR TITLE
Added onMouseEnter and onMouseLeave listeners to action

### PR DESCRIPTION
**Pull request by pouryapb**
## Description
I'm working on a project and I needed these two listeners, so I added them and thought others might need it as well.
I added these as I needed them, but someone could add all listeners

## Impacted Areas in Application
actions

### CODE REVIEW

**Comment by matthewoestreich** [comment]
Are we not able to override the action component to handle those events? 

I believe that is why overriding is allowed - so there's no magic under the hood, etc..

**Comment by pouryapb** [comment]
yes overriding is good but copying the whole code of that component and adding a small piece of code doesn't feel right

**Comment by matthewoestreich** [comment]
Yea, I see what you mean. My train of thought was to try and limit the amount of props, as it starts to get confusing. But I think I agree with you - it's just cleaner to add those props. @Domino987 what do you think?

Before adding them, we need to make sure they get [documented as well](https://github.com/material-table-core/website).

---

Just for the record, something like this is what I had in mind:

```js
function OverrideAction(props) {
  return (
    <MaterialTable
      actions={[
        {
          icon: 'save',
          tooltip: 'Save User',
          onClick: (event, rowData) => alert('You saved ' + rowData.name)
        }
      ]}
      components={{
        Action: (props) => (
          <div onMouseEnter={e=>console.log({props})&&alert('onMouseEnter fired - check console')}>
            <MTableAction {...props} />
          </div>
        )
      }}
      data={[
        { name: 'jack', id: 1 },
        { name: 'nancy', id: 2 }
      ]}
      columns={[
        {
          field: 'name',
          title: 'Name',
          hiddenByColumnsButton: true
        },
        { field: 'id', title: 'Identifier', type: 'numeric' }
      ]}
    />
  );
}
```

**Review by Domino987 — COMMENTED** [review]
While i agree that we should not expose too many props I think this could be a good idea. Alternatively we also could add a feedback handler that gets spreaded onto the  component to reduce the amount of code we have to write. Some like action={{title:..., Icon:..., Handler: {onBlur...., OnMouseEnter:...}}} And spread them to the component with {...action.handlers}. This would prevent to many top level props and we would not need to implement all the handlers ourselves. @oze4 what do you think. We just need a way to add the data object to those calls.

**Comment by matthewoestreich** [comment]
@Domino987 I agree. I was thinking about spreading as well. Just makes it so much easier.

**Comment by Domino987** [comment]
Maybe something like this:

const onAction = Object.entries(action.handlers ?? {}).reduce((obj, [key, val]) => {
   obj[key] = e => val(e, props.data)
return obj;
},{})
....
{...onAction}

**Comment by matthewoestreich** [comment]
Yea that's nice!

**Comment by matthewoestreich** [comment]
I just made these changes and tested - looks to be working!

**Review by matthewoestreich — APPROVED** [review]

**Comment by matthewoestreich** [comment]
Thank you @pouryapb @Domino987 merged and (about to be) published!

It's also worth noting that I left the existing `onClick` prop (so we don't break existing code). If you use both `onClick`, the one within `handlers.onClick` should win out. Just something to consider.

**Comment by Domino987** [comment]
Yes, i could be moved in there, bit to reduce the mental load and not break existing gift, keeping it is perfect. Since all users want the on click it should be easily accessible. Looks great

**Comment by Domino987** [comment]
I think we need to update the types, since they are still the old ones. I will do that today.

**Pull request merged**
