### PR TITLE
Add animation for detail panel entry/exit

### LINKED ISSUE #252: DetailPanel expand / collapse animation?
Bringing up a [previously requested feature](https://github.com/mbrn/material-table/issues/1566) which never got a resolution:

Would it be possible to have expand/collapse animation when the detail panel is toggled?
Currently is simply appears when toggled on and disappears when toggled off.... doesn't look great.

I have tried using:
`import Collapse from '@material-ui/core/Collapse';`
and wrapping it around the detailpanel output. But it doesn't affect the behavior.

Would this be possible? Any tips?

### PR DESCRIPTION
**Pull request by appukuttan-shailesh**
@oze4: this PR tries to resolve #252 
Here is a first working draft that seems to add the desired behavior. I have also added a new usecase to the demo app that handles multiple detail panels.

Here is a demo of the new feature:
Peek 2021-07-14 18-18

Do let me know what could be improved or requires attention.
This is my first contribution here, so apologies if I haven't followed some specific guidelines.

### CODE REVIEW

**Comment by appukuttan-shailesh** [comment]
p.s. Note that the changes could have been even more minimal if only entry animation was required. This would have sufficed:
```
{
    <Collapse in={Boolean(props.data.tableData && props.data.tableData.showDetailPanel)} timeout="auto" unmountOnExit>
                 {typeof props.data.tableData.showDetailPanel === 'function' ? props.data.tableData.showDetailPanel(props.data) : null}
    </Collapse>
}
```
But to have animation on exit as well, it was necessary to handle 'function' and 'object' as separate cases. `Collapse` itself handles hide/show of its children, and so the rendering of the child elements shouldn't be controlled directly via state parameters but rather via parameter `in` of Collapse. It is therefore required to have the loop rendering each detail panel, when multiple exists.

The good part is that Collapse doesn't simply "hide" the display of its children, but also ensures it isn't rendered in the DOM until required. This helps avoid unnecessary pre-load of detail panel content.

**Review by matthewoestreich — COMMENTED** [review]
What if someone doesn't want this animation? Should this be the default, and **only** setting? Should we make it so you can provide your own animation (maybe a way to override the detail panel component)? @Domino987 thoughts?

**Comment by matthewoestreich** [comment]
@appukuttan-shailesh thanks for this, by the way! Your help/time/contribution is ***greatly*** appreciated, my friend!

**Comment by Domino987** [comment]
I think the animation should be the default. But it is actually quite tricky because we don't know the size of what is rendered and it might change during renders. 
Also the logic currently of passing the detail panel function into the table data is quite weird and blocks this. Because we cannot render an exit animation because it's just gone on close. So I like this but it's not as straight forward as it seems.

**Comment by matthewoestreich** [comment]
Works for me (I agree btw) just wanted your opinion! Thank you.

**Review by matthewoestreich — APPROVED** [review]

**Comment by matthewoestreich** [comment]
@appukuttan-shailesh you should see these changes in v3.0.17. Thank you!

**Comment by matthewoestreich** [comment]
@Domino987 if we get a bunch of issues on this, we can revert these changes so we can figure out a better way.

**Comment by Domino987** [comment]
Yes but I think this looks good. We will see :)

**Comment by oze4** [comment]
Yea I like it how it is. Almost like separation of concerns (or functions). Just easier to read like it is imo.

**Comment by appukuttan-shailesh** [comment]
Thanks @oze4  and @Domino987 ! Happy to see this accepted and included in the package.

I had wondered if to add another paramter to allow turning this animation on/off. But decided to keep changes minimal, unless requested explictly. I too felt it would be nice to keep the animation as the default behavior, and so went with it. Curious to see if any other aspect got affected unknowingly.

Thanks for making the 3.0.17 release quickly!

**Pull request merged**
