### PR TITLE
fix: persist row click events, single and double click

### PR DESCRIPTION
**Pull request by matthewoestreich**
## Related Issue

#278

### CODE REVIEW

**Comment by Domino987** [comment]
Yes this seems like an artifact from the code when I played with it. The third param. I am not sure if persisting is the best choice.
This should only be used for async callbacks and if the user uses async callbacks, like setState, he can easily extract it. This also only applies for react < 17. It should not be a problem with React >= 17 because the event pooling is removed. And the persisting might lead to some performance issues but I don't think this will be the case here. So it seems like a band-aid to the problem but if this fixes it why not.

**Review by Domino987 — APPROVED** [review]

**Comment by Domino987** [comment]
Can we add that to the types as well?

**Comment by matthewoestreich** [comment]
Are you referring to the `persistEvents` prop? If so, that was just done for cleanliness. That prop shouldn't need to be in they `types/index.d.ts` file. 

I just made it so that if we wanted to do something like that, and expose the persistEvents prop publicly, it would be easier to integrate it if I wrote this PR like I did. 

**As of right now, the default is "all row click events are persisted"**.

Or am I missing something?

**Comment by Domino987** [comment]
No that's fine, i thought you wanted to add it to the global props as well. Bit this is perfect.

**Comment by matthewoestreich** [comment]
I just saw this..

>This should only be used for async callbacks and if the user uses async callbacks, like setState, he can easily extract it. This also only applies for react < 17. It should not be a problem with React >= 17 because the event pooling is removed. And the persisting might lead to some performance issues but I don't think this will be the case here. So it seems like a band-aid to the problem but if this fixes it why not.

I had some concerns with persisting as well.. Should we persist by default across the board, or should we expose that prop publicly?  I honestly don't know much about the issues using persist can cause. If you don't think we should persist, then I agree with you (the truth is this issue can be solved without access to `event.target`, as you said).

**Comment by Domino987** [comment]
Maybe let's not persist it and they should just get their code in order...

**Comment by oze4** [comment]
I agree. So I started writing it to force the consumer to override the `MTableBodyRow` component, but I think I'm missing something really small because unless I use `propTypes` to set the default value for `persistEvents` it's like it ignores the overridden value.

I wonder if there's an issue with overriding components (the override demo on the website is working fine tho)?

When you have some time, I could use a second pair of eyes on this.

The demo is called `EventTargetErrorOnRowClick`.

Even though I am setting the prop when overriding, it's like it gets ignored?

https://github.com/material-table-core/core/blob/48a08aa35afcdf7afd67f22efdf7ab9f0d94ed0b/__tests__/demo/demo-components/index.js#L545-L561

**Comment by matthewoestreich** [comment]
Hey @Domino987 I tend to agree with you.

Here is what I have changed.. 

- **Events *are no longer persisted* by default**
- The consumer has to override Row if they want to persist events
  - This is because we want to make sure the consumer understands what it is they're doing, thus accepting liability
- The consumer does not need to provide table props for onSelectionChange or onRowClick when overriding the Row
- The following example shows how to accomplish persisting:

```js
    <div>
      <MaterialTable
        title={'EventTargetErrorOnRowClick'}
        tableRef={tableRef}
        columns={cols}
        data={datas}
        // onSelectionChange={onRowSelectionChanged}
        // onRowClick={onRowClicked}
        components={{
          Row: (props) => {
            return (
              <MTableBodyRow
                {...props}
                persistEvents={true}
                onRowClick={onRowClicked}
                onRowSelected={onRowSelectionChanged}
              />
            );
          }
        }}
        options={{
          selection: true
        }}
      />
    </div>
```

Thoughts?

**Comment by Domino987** [comment]
I think that's perfect. It births gives the user the chance to do it but reduces problem for other users. I really like it

**Pull request merged**
