### PR TITLE
converted MTableCell class component to functional component

### PR DESCRIPTION
**Pull request by MrWittman612**
## Related Issue
Class component refactor

## Description
Refactor MTableCell class to a functional component

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Impacted Areas in Application

List general components of the application that this PR will affect:

\*

## Additional Notes

I changed this from the last version I did. In this one, I turned the render into a function called render and just returned the render

### CODE REVIEW

**Review by Domino987 — CHANGES_REQUESTED** [review]
Looking good, but can we remove the default imports to named imports? They cause a lot of trouble in the long run?

**Review by Domino987 — CHANGES_REQUESTED** [review]
Can we return the render directly instead of creating a new function to be called upon return?

**Comment by matthewoestreich** [comment]
Good point @Domino987 this also reminds me we need a better bundler. Or at least better options in babel. We should only be shipping a single minified file. In multiple formats.

**Comment by Domino987** [comment]
> Good point @Domino987 this also reminds me we need a better bundler. Or at least better options in babel. We should only be shipping a single minified file. In multiple formats.

I still hope for tsdx 🤞🙂

**Comment by MrWittman612** [comment]
can we set up a time to talk and go over the code on discord?

**Comment by MrWittman612** [comment]
ok I made some changes I think you'll like but as far as converting default imports to named imports can I get an example? I'm  not sure what it is exactly you want to be done with that

**Comment by matthewoestreich** [comment]
@Domino987 I thought we were using TSDX (in the `next` version)?  Are we able to integrate TSDX into an existing project? If so, I say let's do it. 

For now I went ahead and integrated rollup, which bundles/minifies the library down to a single file.

**Comment by matthewoestreich** [comment]
@MrWittman612 I would be willing to commit to a weekly scheduled 'chat'.

**Comment by Domino987** [comment]
> @Domino987 I thought we were using TSDX (in the `next` version)? Are we able to integrate TSDX into an existing project? If so, I say let's do it.
> 
> For now I went ahead and integrated rollup, which bundles/minifies the library down to a single file.

Yes but currently its not a fork, so to take advantage of the whole process, it would need to be a fork instead of a new repo, I will think about it. Add yes I would be down to a weekly chat too.

**Comment by matthewoestreich** [comment]
Should we fork this repo and use that for `next`? I mentioned doing that a couple weeks ago but wasn't sure how you wanted to handle it.

**Comment by Domino987** [comment]
I was thinking the same and since the core repo advances fast, it would be a good idea. I am thinking of forking this to be the next, start a tsdx repo internally and replace everything except the components to be the tsdx project in the next repo. This should keeo it to be a fork but based in tsdx. I am not sure, if this would work, but I will try it tomorrow.

**Comment by MrWittman612** [comment]
I have forked material-table-core/next I could pipe these changes to that repo and then push somehow

**Comment by matthewoestreich** [comment]
@Domino987 I went ahead and removed `rollup` and installed [`esbuild`](https://esbuild.github.io/) for bundling this repo. Although, we can use tsdx if you prefer (I have no preference, really).

It is a million times easier than webpack or rollup and doesn't require a million different plugins. It bundles this library in about 1 second whereas rollup/babel are around 6 seconds.

Not to mention the bundle size..

using-babel

using-rollup

using-esbuild

**Comment by matthewoestreich** [comment]
>but as far as converting default imports to named imports can I get an example? I'm not sure what it is exactly you want to be done with that

@MrWittman612 I think @Domino987 was referring to `import * as X from 'y';` and changing that to `import X from 'y';` - if not, then am in the same boat as you.

**Comment by Domino987** [comment]
> > but as far as converting default imports to named imports can I get an example? I'm not sure what it is exactly you want to be done with that
> 
> @MrWittman612 I think @Domino987 was referring to `import * as X from 'y';` and changing that to `import X from 'y';` - if not, then am in the same boat as you.

Hi I was referring to export default .... , Instead, it's better to declare it, eg. Const x = ... , And export it with export {x} . And import it with import {x} from "v". This makes it a lot more clearer what gets imported and exported without confusion.

**Comment by MrWittman612** [comment]
> > > but as far as converting default imports to named imports can I get an example? I'm not sure what it is exactly you want to be done with that
> > 
> > 
> > @MrWittman612 I think @Domino987 was referring to `import * as X from 'y';` and changing that to `import X from 'y';` - if not, then am in the same boat as you.
> 
> Hi I was referring to export default .... , Instead, it's better to declare it, eg. Const x = ... , And export it with export {x} . And import it with import {x} from "v". This makes it a lot more clearer what gets imported and exported without confusion.

I wanted to use import React, {useState} from 'react' that way I don't have to declare React on ever hook being used. I was wondering how you want me to move forward? should I close all these refactor merge requests and keep them to material-table-next? it would be nice if the two repos were linked so I could just merge these changes to that repo but it didn't seem to be an option. maybe if we just had a branch called next that we push these changes to before merging to core's master? Idk are you going to move again from an npm package core to an npm package next?

**Comment by matthewoestreich** [comment]
@MrWittman612 we are working on getting 'next' to be a fork of 'material-table-core' (which is a fork of 'mbrn/material-table').. Because of this, please keep these PR's open on this repo. Right now the `next` repo is private which should change, @Domino987  what do you think?

As far as importing like you mention, that is fine. @Domino987 was referring to something like this (I think).. I don't necessarily think named exports are a bad thing, but I could be wrong (this package uses both - it's why you can do:

```javascript
import MaterialTable, { MTableToolbar } from '@material-table/core';
//                      ^^^^^^^^^^^^^
```

#### Don't do this

```javascript
// am I being exported? (yes)
const foo = "f"; // could be anything you are exporting
// what about me? am I being exported? (no)
const bar = "b"; 

export {
  foo
};
```

#### Do this instead

```javascript
// This makes it easier to distinguish what is being exported at a glance
// aka inline exports(?)
export const foo = "f"; // could be anything you are exporting
export const bar = "b"; 
```

**Review by matthewoestreich — APPROVED** [review]
Looks good

**Pull request merged**
