### PR TITLE
Use babel-plugin-import on @material-ui libraries

### PR DESCRIPTION
**Pull request by ymor**
## Related Issue

#435

## Description

Change the @material-ui imports on build.

### CODE REVIEW

**Comment by matthewoestreich** [comment]
What does this do for this project? What benefits does this give us? Also, it looks like tests are breaking. Not sure if that has anything to do with this or not.

**Comment by ymor** [comment]
Currently if I use this library, webpack isn't able to tree shake the material-ui/icons so I ended up with all the icons in my bundle.  This changes the imports so that webpack can effectively tree shake them.  It's essentially the same issue as https://github.com/material-table-core/core/issues/418 but in the current version of this library.  I'll look at fixing the tests.

**Comment by matthewoestreich** [comment]
Is this for the @next branch? Or are all icons being bundled in v4.x? Nice find!

**Comment by ymor** [comment]
This is for V4.x .  The @next branch was resolved in https://github.com/material-table-core/core/pull/421. I believe it cropped in when the default icons were added: https://github.com/material-table-core/core/pull/410 .

**Comment by matthewoestreich** [comment]
Ok cool. Looks like @Domino987 is on it (or is at least more aware of this than I am). So then once we get tests working, we should be good to merge this?

**Review by matthewoestreich — APPROVED** [review]
Thank you!

**Pull request merged**
