### PR TITLE
Added missing aria labels to pagination component

### PR DESCRIPTION
**Pull request by vmihalachi**
## Description

Added missing aria labels to the pagination component

## Impacted Areas in Application

Pagination component, Accessibility

## Additional Notes

They were described in the documentation as having a value https://material-table.com/#/docs/features/localization but their actual value was null

### CODE REVIEW

**Review by matthewoestreich — APPROVED** [review]
Looks good to me!

**Comment by matthewoestreich** [comment]
Thank you @vmihalachi !!

**Comment by vmihalachi** [comment]
Thanks @oze4, I appreciate what you guys are doing!

**Comment by matthewoestreich** [comment]
@vmihalachi just saw this, and thank you very much! It feels good to hear that. 

Butttt 

>you guys

I wish I could take credit, but it's what *we* (including you, per this commit) are doing **together** that makes this awesome! :smile:

Cheers.

**Pull request merged**
