### PR TITLE
M table refactor

### PR DESCRIPTION
**Pull request by MrWittman612**
## Related Issue

converted all components to functional components

## Description

every component has been converted to a functional component 

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Impacted Areas in Application

List general components of the application that this PR will affect:

\*
everything
## Additional Notes
all thou this is a very good start there is more simplification that  can be done as well as memoization 
This is optional, feel free to follow your heart and write here :)

### CODE REVIEW

**Comment by matthewoestreich** [comment]
Oh wow!!! This is incredible. I will take a look at this now and let you know if I have questions. 

Have these changes been tested at all?

**Comment by matthewoestreich** [comment]
@Domino987 would also need to review this before we merge as well as conflicts resolved.

**Comment by MrWittman612** [comment]
I really think there should be more work done to this before merging. I think more simplifications can be made and the use of callback and memoization hooks should or could be implemented, and lazy initialize the useState hooks(maybe).

**Comment by MrWittman612** [comment]
I think I messed up refactoring MTableToolbar in the M-table-body I turned the render into a function and returned the render function and that worked. but that's not how I did it in MTableToolbar just a little heads up

**Review by matthewoestreich — COMMENTED** [review]
Instead of using `function Foo(props) { ...` do you think we should destructure props to make it more clear which props the component accepts (and just overall legibility)?

`function Foo({ propOne, propTwo }) { ...` for example

**Comment by MrWittman612** [comment]
> Instead of using `function Foo(props) { ...` do you think we should destructure props to make it more clear which props the component accepts (and just overall legibility)?
> 
> `function Foo({ propOne, propTwo }) { ...` for example

I tried it didn't work but I started from the bottom up which you might have to work from the top-down pass the props declaratively but once the code is converted to typescript that refactoring will happen. I think this is just a good place to start that process from

**Comment by matthewoestreich** [comment]
Someone else also submitted #27 which looks to be for the same thing.

I say we should discuss which changes to keep and which to remove, etc.. before merging anything as well.

Thanks for your help on this - awesome stuff!!!

**Comment by MrWittman612** [comment]
> Someone else also submitted #27 which looks to be for the same thing.
> 
> I say we should discuss which changes to keep and which to remove, etc.. before merging anything as well.
> 
> Thanks for your help on this - awesome stuff!!!

read what I said in the gitter feed https://gitter.im/MaterialTableCore/community

**Comment by MrWittman612** [comment]
I'm am going to close this request and make a separate request for each file

**Pull request closed without merging**
