### PR TITLE
Fix Detail Panel remounting on parent state change

### PR DESCRIPTION
**Pull request by TheGoodSpinach**
## Related Issue

#334 

## Description

Today, the detail panel component fully remounts whenever the parent `MaterialTable` rerenders. This is causing many issues as any states saved in the detail panel are lost on remount. I was able to trace this issue down to a syntax discrepancy in the way the `Render` function is called in `m-table-detailpanel.js`. Strangely, calling the Render function like this:

`<Render rowData={props.data} />`

causes the remount, while calling it like this:

`{ Render({ rowData: props.data}) }`

does not. I have no idea why this may be, so if anyone has insight into the inner workings of React and the differences between these two syntaxes, I would be very happy to hear.

## Related PRs

--

## Impacted Areas in Application

Detail Panel

## Additional Notes

This is a secondary github account of the creator of #334

### CODE REVIEW

**Comment by Domino987** [comment]
Hi thanks for this pr.
I am thinking about rewriting the original implementation of mbrn to be more stable.
So far the remounting is quite undesired but I am unsure wether or not this change fixes it. 
Can you verify if hooks for example still work and everything regarding the different calling in Jsx vs plain function?

**Comment by TheGoodSpinach** [comment]
Thanks for taking a look @Domino987!

Everything seems to be working as expected after the change, including any hooks inside the detail panel.

Regarding the syntax difference, according to the [react docs](https://reactjs.org/docs/jsx-in-depth.html), calling a component with the syntax `<Component>` is syntax sugar for calling `React.createElement`. I assume that this is why the component is getting re-instantiated every render (as we are calling `React.createElement` every render). For some reason, React is unable to reconcile this element with the previous render's element, which is why it gets fully remounted.

When we instead call it as a function, `Component()`, React implements the already existing React element, that was instantiated by the parent component in this case.

**Comment by TheGoodSpinach** [comment]
Hey @oze4, @Domino987, Is it possible to take another look at this? This bug is blocking us from upgrading.

Thank you!

**Comment by jetro4u** [comment]
When will this pr be fixed?

**Comment by Domino987** [comment]
Merging this will most likely cause other stuff to break, so I am reluctant to merge this right now.
I do not know when I will find the time to rewrite the original implementation but most likely next week. 
Anybody who wants to help can either try to improve the implementation by not passing the panel via the table data of each object or can verify if this solution will not break any existing projects.

**Comment by Domino987** [comment]
I decided to mere this and hope that the problems will be fixed until I get around rewritting the whole detail panel thing.

**Pull request merged**
