### PR TITLE
Data Id

### PR DESCRIPTION
**Pull request by Domino987**
## Related Issue

A bunch of issues that relate to state resets

## Description

This PR fixes a bunch of issues relating to resets of state.
On the one hand, a possible id of each row is added to persist selection, edit, search etc states between renders.
This is optional and the index will be used as fallback and behave just as it was previously.

Additionally, a few warnings are added in development mode:

1. If no id of the rows is provided, a warning will be casts to provide one to reduce the state loss.
2. If the columns contain functions that change on every render, but the remaining columns stay the same (which triggers a state reset ) will now also show a warning to create a stable object or function reference or provide ids.

### CODE REVIEW

**Comment by Domino987** [comment]
@oze4 What do you think

**Comment by kkirsche** [comment]
What constitutes a stable function? Is that a `useCallback` function or something different?

EDIT:

For anyone else landing here and a bit confused, this can be caused by inline `render` functions that leverage a variable, such as `classes` from outside of the function's scope itself. To fix, you can use `useCallback` to make the function stable, and then provide that to the columns definition.

**Comment by matthewoestreich** [comment]
Thank you @kkirsche!

**Comment by WesleySpellman** [comment]
@oze4 @kkirsche Thanks for your work on this project. Could you share a demo on how this new feature can be implemented please?

**Comment by kkirsche** [comment]
Can you clarify the question, @WesleySpellman? The feature will automatically trigger based on what your table definition is, so without a better understanding of what you want demonstrated, I’m not sure how to help

**Comment by WesleySpellman** [comment]
I've set all of my inline render functions to use the useCallback function (like below) - but still receiving the same console warning: 

"The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss."

`  const handleCheckBoxChange = useCallback((form: Form, checked: boolean) => {
    updateTableData(form.key, form.version, form.deliveryOverride, checked);
  }, [updateTableData]);`

I'm calling handleCheckBoxChange in my column definition on an inline render, as shown below:

`{
            title: 'Published',
            render: (rowData: TableAvailableForm) => (
              <Checkbox
                onChange={(_, checked) => handleCheckBoxChange(rowData, checked)}
              />
            ),
          },`

I feel like I'm missing a trivial part of the implementation. Thanks!

**Comment by Domino987** [comment]
Can you share the full code pls?

**Comment by WesleySpellman** [comment]
```
import MaterialTable from '@material-table/core';
import MaterialTableIcons from '../MaterialTableIcons';
import { Form } from './Types';
import Checkbox from '@material-ui/core/Checkbox';
import { useForm, useFieldArray } from 'react-hook-form';
import { useCallback, useEffect } from 'react';

interface Props {
  loading: boolean;
  existingForms: Form[];
  updateTableData: (
    formKey: string,
    formVersion: number,
    overrideEmail: string | null,
    publish: boolean | null
  ) => void;
  setUpdatedAvailableForms: (stateUpdatedAvailableForms: Form[]) => void;
}

interface IFormData {
  availableForms: Form[];
}
interface TableAvailableForm extends Form {
  id: string;
  tableData: {
    id: number;
  };
}


const Table = ({ loading, existingForms, updateTableData }: Props) => {
  const {
    control,
    formState: { errors },
    reset,
  } = useForm<IFormData>({
    defaultValues: {
      availableForms: existingForms,
    },
  });

  const { fields } = useFieldArray({
    control,
    name: 'availableForms',
  });

  useEffect(() => {
    reset({
      availableForms: existingForms,
    });
  }, [reset, existingForms]);


  const handleCheckBoxChange = useCallback((form: Form, checked: boolean) => {
    updateTableData(form.key, form.version, form.deliveryOverride, checked);
  }, [updateTableData]);

  return (
    <form noValidate>
      <MaterialTable<Form>
        isLoading={loading}
        icons={MaterialTableIcons}
        title="Forms"
        columns={[
          {
            title: 'Published',
            render: (rowData: TableAvailableForm) => (
              <Checkbox
                onChange={(_, checked) => handleCheckBoxChange(rowData, checked)}
              />
            ),
          },
        ]}
        data={fields ?? []}
        options={{
          search: true,
          pageSize: 20,
          pageSizeOptions: [10, 20, 50],
        }}
      />
    </form>
  );
};

export default Table;
```

**Comment by Domino987** [comment]
Ah see, you are not actually memorization the render function but just the function that is being called from the render function.

You are still generating a new function on every render with () => ...

Try this:
```
const Table = ({ loading, existingForms, updateTableData }: Props) => {
  const {
    control,
    formState: { errors },
    reset,
  } = useForm<IFormData>({
    defaultValues: {
      availableForms: existingForms,
    },
  });

  const { fields } = useFieldArray({
    control,
    name: 'availableForms',
  });

  useEffect(() => {
    reset({
      availableForms: existingForms,
    });
  }, [reset, existingForms]);

   const renderCheckbox = useCallback(
    (rowData: TableAvailableForm) => (
      <Checkbox
        onChange={(_, checked) => updateTableData(form.key, form.version, form.deliveryOverride, checked)}
      />
    ),
    [updateTableData, form]
  );

  return (
    <form noValidate>
      <MaterialTable<Form>
        isLoading={loading}
        icons={MaterialTableIcons}
        title="Forms"
        columns={[
          {
            title: 'Published',
            render: renderCheckbox
          },
        ]}
        data={fields ?? []}
        options={{
          search: true,
          pageSize: 20,
          pageSizeOptions: [10, 20, 50],
        }}
      />
    </form>
  );
};
```
Also you have an error, since you pass rowData to handleCheckBoxChange, but it actually accepts the form.
In my version this is corrected,

**Comment by tamilarasu602** [comment]
The column equality check is run even when the `columns` prop is not changed and only the `data` prop is updated. Refer code
```
if (!this.isRemoteData()) {
  propsChanged = propsChanged || !equal(prevProps.data, this.props.data);
}
```

So, the column warning is shown even when the column's function did not change between the renders. 
This warning causes confusion in such cases.

Example column definition that causes issue
```
const columns = [
  { title: "Name", field: "name" },
  {
    title: "Date of birth",
    field: "dob",
    render: (rowData) => customFormat(dob),
  },
];

export default function Table() {
  const [data, setData] = useState([]);
  // Fetch data from API
  return <MaterialTable columns={columns} data={data} />;
}
```

**Comment by matthewoestreich** [comment]
The render function you provided isn't stable though, that's why it keeps happening (if I'm understanding correctly).

**Comment by Domino987** [comment]
Yes, the function changes, just not what it does.

**Comment by tamilarasu602** [comment]
> Yes, the function changes, just not what it does.

The render function in columns doesn't change, because it is defined outside the component and so it will get created only once. I have tried defining columns inside the component body and using `useCallback` as suggested above, but the issue still happens.

I want to focus on a bug in this change, which is
- **If the data prop changes and the column prop(which contains a function in one of its keys) doesn't change, then in that case too, this warning will be shown.**
- The warning doesn't show up when there is no key in the columns that has a function in it and the data changes. Because we check for that in `bothContainFunctions` variable.

This is because the logic behind this change is 
- Compute if props changed (Includes column and data property - Lines `139 - 144`)
- If props changed and if not previously checked for warning, then check if both the current and previous columns have a function in them, if yes, then do the below check.
- The check removes all keys that have function value and checks if the remaining columns object is equal. (This steps assumes that something in columns is changed, but that is not necessarily the case). 

An ideal fix for this would be to run the warning check only when the columns prop changed
i.e `!equal(fixedPrevColumns, fixedPropsColumns)` is true

**Comment by Domino987** [comment]
Oh you are of course right. I oversaw that the columns were created above the function.
Yes your idea is right and should fix it. Would you mind creating a PR with this fix?

**Comment by matthewoestreich** [comment]
I'm confused lol.. Even if it is defined outside of the function wouldn't react still treat it as a new object? (and thus a new function)? 

It sounds like you all are on the right track, though, so I will let you both work your magic!  Thanks very much @tamilarasu602

**Comment by Domino987** [comment]
> I'm confused lol.. Even if it is defined outside of the function wouldn't react still treat it as a new object? (and thus a new function)?
> 
> It sounds like you all are on the right track, though, so I will let you both work your magic! Thanks very much @tamilarasu602

No because it checks for object reference of the function and the reference stays the same. But we need to fine tune it s bit

**Comment by WesleySpellman** [comment]
Thanks for the advice & bug fix :)

**Comment by jetro4u** [comment]
I am using a Class component where I can't implement useCallball hook. My table was working fine in MT without the unique id column. In MT/core I introduced the id but still getting the error because I have a render column that fetches data and render. 
```
The columns provided to material table are static, but contain functions which update on every render, resetting the table state. Provide a stable function or column reference or an row id to prevent state loss. 
```
Below is my full code. I have removed unneccessary functions.

```
class SectionTable extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
		this.columnStruct = [
			{ title: 'Id', field: 'id' },
			{
				title: 'Question',
				render: (row) => {
					return <div className="td-element"><div className="truncate">{row.text}</div></div>
				},
				sorting: false,
			},
			{
				title: 'Score',
				field: 'responses.0.score',
				sorting: false,
			}
		];
	}

	fetchQuestions = (query) => {
	}

	render() {
		return (
			<div className="overview-container">
				<h2 className="sup-header inline-block sup-header-edit">Section</h2>
				<MaterialTable
					data={this.fetchQuestions}
					title=" "
					tableRef={this.tableRef}
					columns={this.columnStruct}
					detailPanel={[
					  {
						tooltip: 'Section Table',
						render: ({ row, rowData }) => {
							let qId = rowData.questionTypeId === QuestionTypes.CUSTOM
								&& Array.isArray(rowData.options) && rowData.options[0] ? rowData.options[0].text : '';
					
							switch(qId) {
								case 'sec-5':
									return (
										<div className="detail-panel">
											<Section5
												q={rowData}
												disabled={this.state.disabled}
												saveAnswer={this.saveAnswers}
												update={this.update}
											/>
										</div>
									);
								default:
									return (
										<div className="detail-panel">
										</div>
									);
							}
						}
					  }
					]}
					options={offline ? {
						search: false,
						selection: false,
						filtering: false,
						paging: false
					} : {
						pageSize: 10,
						exportButton: false,
						headerStyle: {
							backgroundColor: '#0386ba',
							color: '#FFF'
						},
						pageSizeOptions: [10, 50, 100],
						emptyRowsWhenPaging: false,
						thirdSortClick: false,
					}}
					icons={tableIcons}
					style={{ width: '100%' }}
				/>

			</div>
		);
	}
}

export default SectionTable;
```
In my previous usage I define the detailPanel as a function below

```
	detailPanel = (row) => {
		let qId = row.questionTypeId === QuestionTypes.CUSTOM
			&& Array.isArray(row.options) && row.options[0] ? row.options[0].text : '';

		switch(qId) {
			case 'sec-5':
				return (
					<div className="detail-panel">
						<Section5
							q={row}
							disabled={this.state.disabled}
							saveAnswer={this.saveAnswers}
							update={this.update}
						/>
					</div>
				);
			default:
				return (
					<div className="detail-panel">
					</div>
				);
		}
	}
```
and I call it inside the MT table as ```detailPanel={this.detailPanel}```

 In section 5 question component table, when the user enter values there is a function that calculate the values and show the total in another cell. Now for the total to show I need to navigate away from the page and reload the page to change the state for each row calculation.

How can this PR fix this issue

**Comment by kkirsche** [comment]
Class components usually can use bound methods. `useCallback` is often meant to generate a deferentially maintained property from one component to another. A bound method on the class should already be this.

https://stackoverflow.com/questions/60344321/how-to-convert-functional-component-using-hooks-to-class-component#60344878 what comes to mind. I'd need to review your example in detail to see if you're doing anything unique though.

**Pull request merged**
