### PR TITLE
Add forwardRef to each functional component

### PR DESCRIPTION
**Pull request by Domino987**
## Related Issue

#73
## Description

We need to add a forwardRef wrapper around all default exports and pass the ref to the first child in the final return. I started with the EditRow but work on the other components soon. Help is appreciated ;)

Like this:
```
export default React.forwardRef(function MTableWithRefEditRow(props, ref) {
  return <MTableEditRow {...props} forwardedRef={ref} />;
});
```
and 
```
 <TableRow
        onKeyDown={handleKeyDown}
        {...rowProps}
        ref={forwardedRef} // THis ref is not passed to the row
        style={getStyle()}
      >
```

### CODE REVIEW

**Comment by Domino987** [comment]
@oze4 SO I added all the function components with forwardRef.
Can you verify that it still all works for you?

**Review by matthewoestreich — APPROVED** [review]

**Comment by matthewoestreich** [comment]
@Domino987 still getting some errors..

Screen Shot 2021-01-22 at 1 42 42 PM

**Comment by matthewoestreich** [comment]
If you run `npm start` you'll see them.

**Comment by matthewoestreich** [comment]
FYI - worth noting that it doesn't even render anymore.

**Comment by Domino987** [comment]
Yes I will go through all of them one by one now, but the basic code is done.

**Comment by matthewoestreich** [comment]
@Domino987 nice work! I'll help out. I saw you were on a roll with adding the ref so I left it alone lol

**Comment by Domino987** [comment]
Ok I will try it out on monday and merge it afterwards

**Comment by matthewoestreich** [comment]
@Domino987 I just had a thought...do you think we should use `useRef` instead of `createRef` since we are moving to a functional standard anyhow?

**Comment by Domino987** [comment]
Yes, but where are we using the create ref currently?

**Comment by matthewoestreich** [comment]
Apologies, I meant forward ref. Is there a hook for forwardRef? My bad, I was wrong. I thought we were integrating createRef.

I've been refactoring data-manager to be more hooks based (use context and use reducer) and useRef crossed my mind, then I commented a little too quickly lol

**Comment by Domino987** [comment]
So I plan on merging this on Wednesday after testing it a bit more.

**Pull request merged**
