### PR TITLE
[Contribution] WCAG Coverage Improved

### PR DESCRIPTION
**Pull request by edgar-arroyo-by**
## Description

They are some WCAG Issues on the MaterialTable, for example on the header. 

Let me explain them:

### Nested Interactive issue:
Say you are using _sorting_, and also _drag&drop_ features, both at the same time.
At DOM level, you have an MuiButtonBase span, which is the TableSortLabel and then inside of it, the draggable component.

Because the TableSortLabel has by default the role='button' attribute, and inside of it is a draggable component, WCAG marks an error of Nested Interactive issue, https://dequeuniversity.com/rules/axe/4.3/nested-interactive?application=axeAPI

A hotfix is to left the TableSortLabel  with an empty role. 
image

**Another case is this one:**

Say the user wants to add a, lets say, checkbox on the header, or another interactive field, and say the user wants to use the draggable feature in all the columns but disable that one, so that's why this PR adds the ability to use the drag&drop feature but to disable it in a particular column setting the draggable property to false.

image

This is not a breaking change because draggable can be undefined and the drag&drop feature will work.

### Accessible Names

The the user wants a column with an empty column name, this will raise the WCAG Ensures elements with an ARIA role that require parent roles are contained by them issue.

That's why I added the ariaLabel column property
image

So even if the dev left a column without name, if an ariaLabel is set, screen readers will be able to name the column for accessibility users.

**THIS PR does not include any breaking change**

## Impacted Areas in Application

List general components of the application that this PR will affect:

- MTableHeader

## Additional Notes

Thanks for this amazing project!

### CODE REVIEW

**Review by Domino987 — APPROVED** [review]

**Comment by Domino987** [comment]
Seems like we have some kind of error. Can you check it? But very nice issue.

**Comment by edgar-arroyo-by** [comment]
Yep, let me check it :D

👯

**Comment by edgar-arroyo-by** [comment]
Hello there @Domino987 

I already fixed the thing that was breaking the workflow.

**Quick insight of what I did**

image
Because of the changes done for the sake of WCAG (the ones described above), the TableSortLabel does not have the button role anymore, so that's why now by role there is just one button (drag&drop div) and not two as before ( drag&drop div and  TableSortLabel)

What I did to cover the TableSortLabel was to add a data-testid and test it with that below.

**Comment by edgar-arroyo-by** [comment]
I would recommend little by little to use more data-testid, kind of more exact and robust :)

**Comment by edgar-arroyo-by** [comment]
@oze4  would you please review this? :)

Very Pretty Thanks in advance!!!
🕺🏽 👯‍♀️

**Comment by edgar-arroyo-by** [comment]
It seems Checks have passed @Domino987  🥇 🍡 🕺🏽

**Review by Domino987 — APPROVED** [review]

**Comment by edgar-arroyo-by** [comment]
hello there @Domino987  @oze4  

Hope you are doing great!!!

Is there any tentative date for a release? thanks in advance!

**Pull request merged**
