### PR TITLE
M table refactor

### PR DESCRIPTION
**Pull request by naimbouallagui**
## Related Issue

Relate the Github issue with this PR using `#`

## Description

Simple words to describe the overall goals of the pull request's commits.

## Related PRs

List related PRs against other branches:

| branch              | PR       |
| ------------------- | -------- |
| other_pr_production | [link]() |
| other_pr_master     | [link]() |

## Impacted Areas in Application

List general components of the application that this PR will affect:

\*

## Additional Notes

This is optional, feel free to follow your hearth and write here :)

### CODE REVIEW

**Comment by Domino987** [comment]
Great, ty. Can you resolve the merge conflicts first 😊

**Comment by naimbouallagui** [comment]
i'm checking the conflicts

**Review by Domino987 — APPROVED** [review]
Looks good to me. The only one missing the main material table component

**Comment by Domino987** [comment]
@oze4 What do you think?

**Comment by matthewoestreich** [comment]
Looks good to me!

**Comment by naimbouallagui** [comment]
@oze4 @Domino987  Great ! i will change the main material table component to FC . also i think it will be good if we change the components by using destructuring of props (that will looks a clean code and reusable when will migrate to typescript) ! isn't it ?

**Review by matthewoestreich — CHANGES_REQUESTED** [review]
Should we review #28 as well? It looks like we have two PR's for the same thing.

@Domino987

**Comment by naimbouallagui** [comment]
> Should we review #28 as well? It looks like we have two PR's for the same thing.
> 
> @Domino987

@oze4 @Domino987  we can choose one of them they look the same,

**Comment by matthewoestreich** [comment]
It doesn't matter to me which we choose. I'm open to using whichever we choose - just let me know. 👍

**Comment by naimbouallagui** [comment]
So we can choose this one #27 ! @Domino987

**Comment by matthewoestreich** [comment]
@MrWittman612 do you think it's ok to close this one out as well or are you still using it as a reference?

Cannot thank you enough for your help!!!! <3

**Comment by naimbouallagui** [comment]
> @MrWittman612 do you think it's ok to close this one out as well or are you still using it as a reference?
> 
> Cannot thank you enough for your help!!!! <3

@oze4 @MrWittman612 it looks great that we are ready to help each other for going further, whatever the code or PR that we will choose , the important that we are agree with what will change

**Comment by matthewoestreich** [comment]
@MrWittman612 I am starting to merge all of the other PR's - would you mind resolving conflicts please? I'll get them merged ASAP.

**Comment by MrWittman612** [comment]
> @MrWittman612 I am starting to merge all of the other PR's - would you mind resolving conflicts please? I'll get them merged ASAP.

how do I do that?

**Comment by MrWittman612** [comment]
> @MrWittman612 I am starting to merge all of the other PR's - would you mind resolving conflicts please? I'll get them merged ASAP.

I have looked at the code and I really would not refactor like this. creating the file as the index.js is not the best solution In my opinion. It will be better to keep it as the name file M-table-whatever.js but export that file as the index 

   folder name --
                            \
                              M-whatever.js
                              M-whatever.test.js
                              M-whatever.storybook.js
                              M-whatever.mdx
                              index.js

  // index.js

  import {M-whatever} from 'M-whatever;

 export default M-whatever

// whatever file
import M-whatever from './src/component/M-whatever';

**Pull request closed without merging**
