### PR TITLE
Enhanced remote data

### PR DESCRIPTION
**Pull request by ckchiu2**
## Related Issue

#457 
#703 - `props.page` and `props.totalCount` is still not used

## Description

See #654, this is a rework of that branch because that branch is messed up when merging.
This time I add a [sandbox](https://codesandbox.io/p/github/ckchiu2/material-table-core-fork-core/enhance-remote-data-code-sandbox?file=%2F__tests__%2Fdemo%2Fdemo.js&selection=%5B%7B%22endColumn%22%3A17%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A17%2C%22startLineNumber%22%3A12%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cldvtzc510014fwgb8g854mff%2522%252C%2522openFiles%2522%253A%255B%2522%252F__tests__%252Fdemo%252Fdemo-components%252FRemoteData%252Findex.js%2522%252C%2522%252FREADME.md%2522%252C%2522%252F__tests__%252Fdemo%252Fdemo.js%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cldvtzf9300153o6ms5z6f6nm%2522%253A%257B%2522key%2522%253A%2522cldvtzf9300153o6ms5z6f6nm%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A8080%252C%2522key%2522%253A%2522cldvu1cj401tu3o6m98n805s7%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cldvu1a2e01rd3o6mk7y6l1w9%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cldvtzf9300153o6ms5z6f6nm%2522%252C%2522spacesOrder%2522%253A%255B%2522cldvtzf9300153o6ms5z6f6nm%2522%255D%252C%2522hideCodeEditor%2522%253Atrue%257D) preview to the changes.
And because I used codesandbox for development, I can now update package-lock.json. Hail codesandbox lol
Note that #703 is still not fixed. I decided to use them for the remote data only because local paging may mess up sorting (see #662, #670)

## Related PRs

#654 This is a rework of that PR because that branch is messed up

## Impacted Areas in Application

material-table.js (additional logic to handle another type of remote data)
index.d.ts (added isRemoteData type)
demos
package.json (added @reduxjs/toolkit as devDependencies for demo purpose)

### CODE REVIEW

**Comment by Domino987** [comment]
I dont have access to the sandbox link. Can you check it?

**Comment by ckchiu2** [comment]
Can you check the sandbox link again?

**Comment by ckchiu2** [comment]
@Domino987 can you please check again?

**Comment by martin-trajanovski** [comment]
Is this working now? I cannot get it working in my local environment. Still cannot use `page` with custom`totalCount`.

**Pull request closed without merging**
